WebAppFancyTemp/Models/Service_Area.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppFancyTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Area
    {
        public int service_id { get; set; }
        public string service_img { get; set; }
        public string service_title { get; set; }
        public string service_content { get; set; }
        public string service_content_url { get; set; }
    }
}

WebAppFancyTemp/Controllers/Service_AreaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppFancyTemp.Models;

namespace WebAppFancyTemp.Controllers
{
    public class Service_AreaController : Controller
    {
        private FancyTempDBEntities db = new FancyTempDBEntities();

        // GET: Service_Area
        public ActionResult Index()
        {
            return View(db.Service_Area.ToList());
        }

        // GET: Service_Area/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service_Area service_Area = db.Service_Area.Find(id);
            if (service_Area == null)
            {
                return HttpNotFound();
            }
            return View(service_Area);
        }

        // GET: Service_Area/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Service_Area/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "service_id,service_img,service_title,service_content,service_content_url")] Service_Area service_Area,HttpPostedFileBase service_img)
        {
            if (ModelState.IsValid)
            {
                var file_name = Path.GetFileName(service_img.FileName);
                if (service_img.ContentLength > 0)
                {

                    var file_src = Path.Combine(Server.MapPath("/Uploads"), file_name);
                    service_img.SaveAs(file_src);
                }
                service_Area.service_img = file_name;
                db.Service_Area.Add(service_Area);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(service_Area);
        }

        // GET: Service_Area/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service_Area service_Area = db.Service_Area.Find(id);
            if (service_Area == null)
            {
                return HttpNotFound();
            }
            return View(service_Area);
        }

        // POST: Service_Area/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "service_id,service_img,service_title,service_content,service_content_url")] Service_Area service_Area)
        {
            if (ModelState.IsValid)
            {
                db.Entry(service_Area).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service_Area);
        }

        // GET: Service_Area/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service_Area service_Area = db.Service_Area.Find(id);
            if (service_Area == null)
            {
                return HttpNotFound();
            }
            return View(service_Area);
        }

        // POST: Service_Area/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service_Area service_Area = db.Service_Area.Find(id);
            db.Service_Area.Remove(service_Area);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppFancyTemp/Views/Service_Area/Create.cshtml
@model WebAppFancyTemp.Models.Service_Area

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Service_Area", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Service_Area</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.service_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_img, new { htmlAttributes = new { @class = "form-control" , type="file"} })
                @Html.ValidationMessageFor(model => model.service_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.service_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.service_content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.service_content_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_content_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service_content_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebAppFancyTemp/Views/Service_Area/Delete.cshtml
@model WebAppFancyTemp.Models.Service_Area

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service_Area</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.service_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_content_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_content_url)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAppFancyTemp/Views/Service_Area/Details.cshtml
@model WebAppFancyTemp.Models.Service_Area

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Service_Area</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.service_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_content_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_content_url)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.service_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAppFancyTemp/Views/Service_Area/Edit.cshtml
@model WebAppFancyTemp.Models.Service_Area

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Service_Area</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.service_id)

        <div class="form-group">
            @Html.LabelFor(model => model.service_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.service_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.service_content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.service_content_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.service_content_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.service_content_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebAppFancyTemp/Views/Service_Area/Index.cshtml
@model IEnumerable<WebAppFancyTemp.Models.Service_Area>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.service_img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.service_title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.service_content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.service_content_url)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="/Uploads/@item.service_img" style="width:100px;height:100px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.service_title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.service_content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.service_content_url)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.service_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.service_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.service_id })
        </td>
    </tr>
}

</table>