WebAppFancyTemp/Models/Industry.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppFancyTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry
    {
        public int industries_id { get; set; }
        public string industries_title { get; set; }
        public string industries_content { get; set; }
        public string industries_img { get; set; }
        public string industries_url { get; set; }
    }
}

WebAppFancyTemp/Controllers/IndustriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppFancyTemp.Models;

namespace WebAppFancyTemp.Controllers
{
    public class IndustriesController : Controller
    {
        private FancyTempDBEntities db = new FancyTempDBEntities();

        // GET: Industries
        public ActionResult Index()
        {
            return View(db.Industries.ToList());
        }

        // GET: Industries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Industry industry = db.Industries.Find(id);
            if (industry == null)
            {
                return HttpNotFound();
            }
            return View(industry);
        }

        // GET: Industries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Industries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "industries_id,industries_title,industries_content,industries_img,industries_url")] Industry industry, HttpPostedFileBase industries_img)
        {
            if (ModelState.IsValid)
            {
                var file_name = Path.GetFileName(industries_img.FileName);
                if (industries_img.ContentLength > 0)
                {

                    var file_src = Path.Combine(Server.MapPath("/Uploads"), file_name);
                    industries_img.SaveAs(file_src);
                }
                industry.industries_img = file_name;
                db.Industries.Add(industry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(industry);
        }

        // GET: Industries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Industry industry = db.Industries.Find(id);
            if (industry == null)
            {
                return HttpNotFound();
            }
            return View(industry);
        }

        // POST: Industries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "industries_id,industries_title,industries_content,industries_img,industries_url")] Industry industry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(industry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(industry);
        }

        // GET: Industries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Industry industry = db.Industries.Find(id);
            if (industry == null)
            {
                return HttpNotFound();
            }
            return View(industry);
        }

        // POST: Industries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Industry industry = db.Industries.Find(id);
            db.Industries.Remove(industry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppFancyTemp/Views/Industries/Create.cshtml
@model WebAppFancyTemp.Models.Industry

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Industries", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Industry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.industries_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.industries_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.industries_content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.industries_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.industries_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_img, new { htmlAttributes = new { @class = "form-control",type = "file" } })
                @Html.ValidationMessageFor(model => model.industries_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.industries_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.industries_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebAppFancyTemp/Views/Industries/Delete.cshtml
@model WebAppFancyTemp.Models.Industry

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Industry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.industries_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.industries_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.industries_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.industries_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_url)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAppFancyTemp/Views/Industries/Details.cshtml
@model WebAppFancyTemp.Models.Industry

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Industry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.industries_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.industries_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.industries_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.industries_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.industries_url)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.industries_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAppFancyTemp/Views/Industries/Edit.cshtml
@model WebAppFancyTemp.Models.Industry

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Industry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.industries_id)

        <div class="form-group">
            @Html.LabelFor(model => model.industries_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.industries_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.industries_content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.industries_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.industries_img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.industries_img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.industries_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.industries_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.industries_url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebAppFancyTemp/Views/Industries/Index.cshtml
@model IEnumerable<WebAppFancyTemp.Models.Industry>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.industries_title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.industries_content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.industries_img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.industries_url)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.industries_title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.industries_content)
        </td>
        <td>
            <img src="/Uploads/@item.industries_img" style="width:100px;height:100px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.industries_url)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.industries_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.industries_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.industries_id })
        </td>
    </tr>
}

</table>